### PR TITLE
[Frontend] [FEAT] - Add homepage

### PR DESCRIPTION
**Pull request by justDabuK**
I am no designer, but I think this is a good start for a home page, that we can extend once we have more to show off

**Changes**
- removed old stuff default created stuff
- added tailwind as dependency and configured it
- added new view components and routes for
  - login
  - register
  - questions
  - solutions
- wrote down basic home page info into `HomeView.vue` (kept the name Home **View** since all views should have this prefix)

home-page-showcase

### CODE REVIEW

**Comment by TheInspiredConjurer** [comment]
Looks Good for now... Can you add some basic styling... you know, colors and stuff...
Also, the logo...

OQS.svg.. its in the folder

**Comment by justDabuK** [comment]
Ah cool, i was just wondering if we already have a logo 👌🏽

**Comment by justDabuK** [comment]
Actually I'm quite happy with this dark version 🤔 
What do you think? 🤔 
home-page-round-edges

**Comment by TheInspiredConjurer** [comment]
Looks great!

Make it togglable!

Put a `toggle dark mode` on a button for it.

**Comment by TheInspiredConjurer** [comment]
Looks good for now!

**Pull request merged**
